/* ── PRODUTOS ── */

const PRODUCTS = [
  {id:1,  name:"Air fryer compacta",                price:300, cat:"Cozinha"},
  {id:2,  name:"Cafeteira elétrica",                price:150, cat:"Cozinha"},
  {id:3,  name:"Sanduicheira elétrica",             price:100, cat:"Cozinha"},
  {id:4,  name:"Chaleira elétrica",                 price:120, cat:"Cozinha"},
  {id:5,  name:"Liquidificador",                    price:200, cat:"Cozinha"},
  {id:6,  name:"Mixer portátil",                    price:70, cat:"Cozinha"},
  {id:7,  name:"Torradeira",                        price:120, cat:"Cozinha"},
  {id:8,  name:"Grill elétrico",                    price:200, cat:"Cozinha"},
  {id:9,  name:"Panela de pressão elétrica",        price:300, cat:"Cozinha"},
  {id:10, name:"Panela elétrica de arroz",          price:200, cat:"Cozinha"},
  {id:11, name:"Forno elétrico compacto",           price:350, cat:"Cozinha"},
  {id:12, name:"Purificador de água",               price:450, cat:"Cozinha"},
  {id:13, name:"Espremedor de frutas elétrico",     price:100, cat:"Cozinha"},
  {id:14, name:"Batedeira portátil",                price:100, cat:"Cozinha"},
  {id:15, name:"Micro-ondas compacto",              price:450, cat:"Cozinha"},
  {id:16, name:"Processador de alimentos compacto", price:180, cat:"Cozinha"},
  {id:17, name:"Fritadeira sem óleo oven",          price:400, cat:"Cozinha"},
  {id:18, name:"Jogo de panelas antiaderente",      price:200, cat:"Cozinha"},
  {id:19, name:"Frigideira wok",                    price:100, cat:"Cozinha"},
  {id:20, name:"Panela de pressão tradicional",     price:100, cat:"Cozinha"},
  {id:21, name:"Panela funda grande",               price:100, cat:"Cozinha"},
  {id:22, name:"Assadeira de vidro",                price:50,  cat:"Cozinha"},
  {id:23, name:"Forma para bolo desmontável",       price:50,  cat:"Cozinha"},
  {id:24, name:"Forma de pizza antiaderente",       price:50,  cat:"Cozinha"},
  {id:25, name:"Jogo de travessas de vidro",        price:120, cat:"Cozinha"},
  {id:26, name:"Conjunto de potes herméticos",      price:80, cat:"Cozinha"},
  {id:27, name:"Faqueiro inox completo",            price:300, cat:"Cozinha"},
  {id:28, name:"Conjunto de facas profissionais",   price:150, cat:"Cozinha"},
  {id:29, name:"Tábua de corte em bambu",           price:50,  cat:"Cozinha"},
  {id:30, name:"Escorredor de louças inox",         price:100, cat:"Cozinha"},
  {id:31, name:"Porta-temperos giratório",          price:60, cat:"Cozinha"},
  {id:32, name:"Lixeira inox para cozinha",         price:150, cat:"Cozinha"},
  {id:33, name:"Kit utensílios de silicone",        price:80, cat:"Cozinha"},
  {id:34, name:"Pegador de massa inox",             price:30,  cat:"Cozinha"},
  {id:35, name:"Descascador de legumes premium",    price:70,  cat:"Cozinha"},
  {id:36, name:"Ralador multifuncional",            price:50,  cat:"Cozinha"},
  {id:37, name:"Cortador de pizza inox",            price:50,  cat:"Cozinha"},
  {id:38, name:"Concha inox reforçada",             price:40,  cat:"Cozinha"},
  {id:39, name:"Espátula culinária profissional",   price:70,  cat:"Cozinha"},
  {id:40, name:"Jarra de vidro para suco",          price:50,  cat:"Cozinha"},
  {id:41, name:"Kit bowls de vidro",                price:130, cat:"Cozinha"},
  {id:42, name:"Aparelho de jantar completo",       price:350, cat:"Cozinha"},
  {id:43, name:"Jogo americano elegante",           price:100,  cat:"Cozinha"},
  {id:44, name:"Toalha de mesa impermeável",        price:60, cat:"Cozinha"},
  {id:45, name:"Porta-guardanapos decorativo",      price:60,  cat:"Cozinha"},
  {id:46, name:"Suporte para papel toalha",         price:40,  cat:"Cozinha"},
  {id:47, name:"Kit copos de vidro",                price:120, cat:"Cozinha"},
  {id:48, name:"Jogo de taças para vinho",          price:250, cat:"Cozinha"},
  {id:49, name:"Kit canecas cerâmica",              price:120, cat:"Cozinha"},
  {id:50, name:"Garrafa térmica inox",              price:140, cat:"Cozinha"},
  {id:51, name:"Bandeja decorativa",                price:100, cat:"Cozinha"},
  {id:52, name:"Balança digital de cozinha",        price:50,  cat:"Cozinha"},
  {id:53, name:"Cuscuzeira inox",                   price:80, cat:"Cozinha"},
  {id:54, name:"Suporte para tampas de panela",     price:50,  cat:"Cozinha"},
  {id:55, name:"Porta-detergente e esponja",        price:50,  cat:"Cozinha"},
  {id:56, name:"Kit potes para mantimentos",        price:150, cat:"Cozinha"},
  {id:57, name:"Escorredor de pratos duplo",        price:140, cat:"Cozinha"},
  {id:58, name:"Cooktop elétrico portátil",         price:300, cat:"Cozinha"},
  {id:59, name:"Adega compacta",                    price:500, cat:"Cozinha"},
  {id:60, name:"Máquina de suco elétrica",          price:200, cat:"Cozinha"},
  {id:61, name:"Paneleiro de cozinha",              price:220, cat:"Cozinha"},
  {id:62, name:"Panela elétrica multifuncional",    price:220, cat:"Cozinha"},
  {id:63, name:"Pipoqueira elétrica",               price:110, cat:"Cozinha"},
  {id:64, name:"Iogurteira elétrica",               price:100,  cat:"Cozinha"},
  {id:65, name:"Kit churrasco inox",                price:180, cat:"Cozinha"},
  {id:66, name:"Tábua churrasco madeira",           price:100, cat:"Cozinha"},
  {id:67, name:"Conjunto de panelas de vidro",      price:350, cat:"Cozinha"},
  {id:68, name:"Frigideira grill dupla",            price:150, cat:"Cozinha"},
  {id:69, name:"Escorredor de macarrão inox",       price:60,  cat:"Cozinha"},
  {id:70, name:"Torre organizadora cozinha",        price:250, cat:"Cozinha"},
  {id:71, name:"Lava-louças portátil",              price:800, cat:"Cozinha"},
  {id:72, name:"Churrasqueira elétrica portátil",   price:180, cat:"Cozinha"},
  {id:73, name:"Conjunto de panelas gourmet",       price:400, cat:"Cozinha"},
  {id:74, name:"Fondue elétrico",                   price:150, cat:"Cozinha"},
  {id:75, name:"Máquina de crepe",                  price:120, cat:"Cozinha"},
  {id:76, name:"Conjunto refratários cerâmica",     price:160, cat:"Cozinha"},
  {id:77, name:"Kit formas air fryer",              price:60,  cat:"Cozinha"},
  {id:78, name:"Escorredor de alimentos retrátil",  price:50,  cat:"Cozinha"},
  {id:79, name:"Bandeija redonda aperitivos",       price:160, cat:"Cozinha"},
  {id:80, name:"Porta-frios hermético",             price:50,  cat:"Cozinha"},
  {id:81, name:"Suporte para xícaras suspenso",     price:40,  cat:"Cozinha"},
  {id:82, name:"Porta-cápsulas café",               price:70,  cat:"Cozinha"},
  {id:83, name:"Centrífuga de frutas",              price:250, cat:"Cozinha"},
  {id:84, name:"Kit assadeiras vidro",              price:160, cat:"Cozinha"},
  {id:85, name:"Jogo de petisqueiras",              price:100, cat:"Cozinha"},
  {id:86, name:"Máquina seladora a vácuo",          price:180, cat:"Cozinha"},
  {id:87, name:"Panela de ferro fundido",           price:220, cat:"Cozinha"},
  {id:88, name:"Chapa grill ferro",                 price:180, cat:"Cozinha"},
  {id:89, name:"Kit fondue cerâmica",               price:120, cat:"Cozinha"},
  {id:90, name:"Jogo de sousplat elegante",         price:180, cat:"Cozinha"},
  {id:91, name:"Kit assadeiras antiaderentes",      price:160, cat:"Cozinha"},
  {id:92, name:"Escorredor de saladas manual",      price:50,  cat:"Cozinha"},
  {id:93, name:"Adega de mesa compacta",            price:220, cat:"Cozinha"},
  {id:94, name:"Cuscuzeira nordestina alumínio",    price:60,  cat:"Cozinha"},
  {id:95, name:"Sorveteira elétrica compacta",      price:240, cat:"Cozinha"},
  {id:96, name:"Máquina algodão doce",              price:140, cat:"Cozinha"},
  {id:97, name:"Pedra para pizza refratária",       price:80,  cat:"Cozinha"},
  {id:98, name:"Suporte magnético para facas",      price:70,  cat:"Cozinha"},
  {id:99,  name:"Centro de mesa decorativo",        price:140, cat:"Sala de Estar/Jantar"},
  {id:100, name:"Relógio de parede moderno",        price:100, cat:"Sala de Estar/Jantar"},
  {id:101, name:"Luminária de mesa LED",            price:90, cat:"Sala de Estar/Jantar"},
  {id:102, name:"Abajur decorativo",                price:110, cat:"Sala de Estar/Jantar"},
  {id:103, name:"Fita LED decorativa",              price:60,  cat:"Sala de Estar/Jantar"},
  {id:104, name:"Espelho decorativo sala",          price:250, cat:"Sala de Estar/Jantar"},
  {id:105, name:"Quadro decorativo grande",         price:220, cat:"Sala de Estar/Jantar"},
  {id:106, name:"Manta decorativa sofá",            price:130, cat:"Sala de Estar/Jantar"},
  {id:107, name:"Almofadas decorativas",            price:90, cat:"Sala de Estar/Jantar"},
  {id:108, name:"Painel para TV",                   price:280, cat:"Sala de Estar/Jantar"},
  {id:109, name:"Mesa lateral pequena",             price:130, cat:"Sala de Estar/Jantar"},
  {id:110, name:"Estante organizadora",             price:290, cat:"Sala de Estar/Jantar"},
  {id:111, name:"Tapete para sala",                 price:310, cat:"Sala de Estar/Jantar"},
  {id:112, name:"Capa para sofá",                   price:100, cat:"Sala de Estar/Jantar"},
  {id:113, name:"Suporte para plantas",             price:140, cat:"Sala de Estar/Jantar"},
  {id:114, name:"Vasos decorativos",                price:100, cat:"Sala de Estar/Jantar"},
  {id:115, name:"Mesa lateral decorativa",          price:140, cat:"Sala de Estar/Jantar"},
  {id:116, name:"Poltrona decorativa compacta",     price:400, cat:"Sala de Estar/Jantar"},
  {id:117, name:"Aparador compacto",                price:270, cat:"Sala de Estar/Jantar"},
  {id:118, name:"Luminária de piso",                price:140, cat:"Sala de Estar/Jantar"},
  {id:119, name:"Espelho corpo inteiro",            price:350, cat:"Sala de Estar/Jantar"},
  {id:120, name:"Aparador de livros decorativo",    price:100, cat:"Sala de Estar/Jantar"},
  {id:121, name:"Kit velas decorativas luxo",       price:90, cat:"Sala de Estar/Jantar"},
  {id:122, name:"Cortina blackout quarto",          price:120, cat:"Quarto"},
  {id:123, name:"Jogo de cama queen",               price:240, cat:"Quarto"},
  {id:124, name:"Edredom casal",                    price:280, cat:"Quarto"},
  {id:125, name:"Kit fronhas premium",              price:50,  cat:"Quarto"},
  {id:126, name:"Travesseiro viscoelástico",        price:140, cat:"Quarto"},
  {id:127, name:"Protetor de colchão impermeável",  price:100, cat:"Quarto"},
  {id:128, name:"Cabeceira estofada casal",         price:300, cat:"Quarto"},
  {id:129, name:"Mesa de cabeceira",                price:180, cat:"Quarto"},
  {id:130, name:"Puff baú premium",                 price:200, cat:"Quarto"},
  {id:131, name:"Jogo de travesseiros premium",     price:60,  cat:"Quarto"},
  {id:132, name:"Cabeceira box simples",            price:220, cat:"Quarto"},
  {id:133, name:"Jogo de lençóis casal premium",    price:180, cat:"Quarto"},
  {id:134, name:"Arara organizadora premium",       price:150, cat:"Quarto"},
  {id:135, name:"Cabideiro de chão",                price:220, cat:"Quarto"},
  {id:136, name:"Banco sapateira estofado",         price:160, cat:"Quarto"},
  {id:137, name:"Kit cabides de veludo",            price:50,  cat:"Quarto"},
  {id:138, name:"Sapateira compacta",               price:170, cat:"Quarto"},
  {id:139, name:"Sapateira grande",                 price:300, cat:"Quarto"},
  {id:140, name:"Porta-joias espelhado",            price:120, cat:"Quarto"},
  {id:141, name:"Mancebo cabideiro madeira",        price:120, cat:"Quarto"},
  {id:142, name:"Espelho de mesa camarim",          price:140, cat:"Banheiro"},
  {id:143, name:"Kit banheiro em bambu",            price:110, cat:"Banheiro"},
  {id:144, name:"Jogo de toalhas banho",            price:180, cat:"Banheiro"},
  {id:145, name:"Tapete antiderrapante banheiro",   price:70,  cat:"Banheiro"},
  {id:146, name:"Cortina box banheiro",             price:50,  cat:"Banheiro"},
  {id:147, name:"Porta-shampoo para box",           price:50,  cat:"Banheiro"},
  {id:148, name:"Suporte toalha inox",              price:50,  cat:"Banheiro"},
  {id:149, name:"Lixeira banheiro inox",            price:100, cat:"Banheiro"},
  {id:150, name:"Escova sanitária premium",         price:40,  cat:"Banheiro"},
  {id:151, name:"Dispenser sabonete líquido",       price:70,  cat:"Banheiro"},
  {id:152, name:"Kit acessórios banheiro",          price:100, cat:"Banheiro"},
  {id:153, name:"Aquecedor portátil",               price:200, cat:"Banheiro"},
  {id:154, name:"Kit toalhas rosto premium",        price:90,  cat:"Banheiro"},
  {id:155, name:"Porta-escovas de dente",           price:40,  cat:"Banheiro"},
  {id:156, name:"Toalheiro elétrico compacto",      price:300, cat:"Banheiro"},
  {id:157, name:"Aspirador de pó portátil",         price:190, cat:"Lavanderia"},
  {id:158, name:"Ventilador de mesa",               price:110, cat:"Lavanderia"},
  {id:159, name:"Ferro de passar roupa",            price:170, cat:"Lavanderia"},
  {id:160, name:"Tapete antiderrapante cozinha",    price:80,  cat:"Lavanderia"},
  {id:161, name:"Cortina para cozinha",             price:110, cat:"Lavanderia"},
  {id:162, name:"Escada dobrável doméstica",        price:200, cat:"Lavanderia"},
  {id:163, name:"Cesto de roupas dobrável",         price:80, cat:"Lavanderia"},
  {id:164, name:"Varal de chão retrátil",           price:110, cat:"Lavanderia"},
  {id:165, name:"Kit prendedores reforçados",       price:40,  cat:"Lavanderia"},
  {id:166, name:"Tábua de passar roupa",            price:140, cat:"Lavanderia"},
  {id:167, name:"Escova giratória elétrica",        price:180, cat:"Lavanderia"},
  {id:168, name:"Kit baldes organizadores",         price:100, cat:"Lavanderia"},
  {id:169, name:"Rodo inox premium",                price:70,  cat:"Lavanderia"},
  {id:170, name:"Mop giratório",                    price:120, cat:"Lavanderia"},
  {id:171, name:"Kit panos microfibra",             price:50,  cat:"Lavanderia"},
  {id:172, name:"Aspirador robô básico",            price:400, cat:"Lavanderia"},
  {id:173, name:"Lavadora de alta pressão compacta",price:320, cat:"Lavanderia"},
  {id:174, name:"Aspirador vertical",               price:200, cat:"Lavanderia"},
  {id:175, name:"Lavadora portátil",                price:210, cat:"Lavanderia"},
  {id:176, name:"Escova elétrica de limpeza",       price:100, cat:"Lavanderia"},
  {id:177, name:"Porta-chaves decorativo",          price:60,  cat:"Escritório"},
  {id:178, name:"Lanterna recarregável",            price:120, cat:"Escritório"},
  {id:179, name:"Extensão elétrica premium",        price:80,  cat:"Escritório"},
  {id:180, name:"Lâmpada smart Wi-Fi",              price:70,  cat:"Escritório"},
  {id:181, name:"Suporte articulado TV",            price:100, cat:"Escritório"},
  {id:182, name:"Cadeira escritório compacta",      price:300, cat:"Escritório"},
  {id:183, name:"Frigobar mini",                    price:450, cat:"Escritório"},
  {id:184, name:"Climatizador de ar",               price:220, cat:"Escritório"},
  {id:185, name:"Mochila térmica",                  price:110, cat:"Escritório"},
  {id:186, name:"Agenda planner sofisticada",       price:45,  cat:"Escritório"},
  {id:187, name:"Caixa térmica compacta",           price:180, cat:"Área Externa"},
  {id:188, name:"Guarda-sol articulado",            price:200, cat:"Área Externa"},
  {id:189, name:"Kit jardinagem completo",          price:150, cat:"Área Externa"},
  {id:190, name:"Mangueira retrátil jardim",        price:120, cat:"Área Externa"},
  {id:191, name:"Regador decorativo",               price:60,  cat:"Área Externa"},
  {id:192, name:"Cristaleira compacta",             price:350, cat:"Área Externa"},
  {id:193, name:"Kit picnic completo",              price:150, cat:"Área Externa"},
  {id:194, name:"Kit ferramentas domésticas",       price:120, cat:"Ferramentas"},
  {id:195, name:"Furadeira doméstica",              price:200, cat:"Ferramentas"},
  {id:196, name:"Maleta de ferramentas",            price:180, cat:"Ferramentas"},
  {id:197, name:"Nicho organizador cozinha",        price:150, cat:"Ferramentas"},
  {id:198, name:"Porta-retratos decorativo",        price:70,  cat:"Decoração"},
  {id:199, name:"Mesa de centro decorativa",        price:200, cat:"Decoração"},
  {id:200, name:"Cachepot decorativo premium",      price:100, cat:"Decoração"},
];

window.PRODUCTS = PRODUCTS;
